/** @type {import("tailwindcss").Config} */
module.exports = {
  theme: {
    extend: {
      typography: () => ({
        base: {
          css: {
            "--tw-prose-body": "var(--color-base-800)",
            "--tw-prose-headings": "var(--color-base-900)",
            "--tw-prose-lead": "var(--color-base-700)",
            "--tw-prose-links": "var(--color-base-900)",
            "--tw-prose-bold": "var(--color-base-900)",
            "--tw-prose-counters": "var(--color-base-600)",
            "--tw-prose-bullets": "var(--color-base-400)",
            "--tw-prose-hr": "var(--color-base-300)",
            "--tw-prose-quotes": "var(--color-base-900)",
            "--tw-prose-quote-borders": "var(--color-base-300)",
            "--tw-prose-captions": "var(--color-base-700)",
            "--tw-prose-code": "var(--color-base-900)",
            "--tw-prose-pre-code": "var(--color-base-100)",
            "--tw-prose-pre-bg": "var(--color-base-900)",
            "--tw-prose-th-borders": "var(--color-base-300)",
            "--tw-prose-td-borders": "var(--color-base-200)",
            "--tw-prose-invert-body": "var(--color-base-200)",
            "--tw-prose-invert-headings": "var(--color-white)",
            "--tw-prose-invert-lead": "var(--color-base-300)",
            "--tw-prose-invert-links": "var(--color-white)",
            "--tw-prose-invert-bold": "var(--color-white)",
            "--tw-prose-invert-counters": "var(--color-base-400)",
            "--tw-prose-invert-bullets": "var(--color-base-600)",
            "--tw-prose-invert-hr": "var(--color-base-700)",
            "--tw-prose-invert-quotes": "var(--color-base-100)",
            "--tw-prose-invert-quote-borders": "var(--color-base-700)",
            "--tw-prose-invert-captions": "var(--color-base-400)",
            "--tw-prose-invert-code": "var(--color-white)",
            "--tw-prose-invert-pre-code": "var(--color-base-300)",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "var(--color-base-600)",
            "--tw-prose-invert-td-borders": "var(--color-base-700)",
          },
        },
      }),
    },
  },
};
